### ISSUE TITLE
not working on Blender 2.92

### ISSUE THREAD

**Issue by baldonazionale** [macio97/PBR-Materials#3]
this is the error:

Traceback (most recent call last):
  File "E:\BLENDER - SOFTWARE\B2.92\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'PBR-Materials-3'

**Comment by macio97** [comment]
Blender 2.92 is still in Alpha stage, it should be at least in Beta to even start testing the add-on in.

**Comment by shankarsivarajan** [comment]
> this is the error:
> 
> Traceback (most recent call last):
> File "E:\BLENDER - SOFTWARE\B2.92\2.91\scripts\modules\addon_utils.py", line 351, in enable
> mod = **import**(module_name)
> ModuleNotFoundError: No module named 'PBR-Materials-3'

The error persists in Blender 2.93.

**Comment by marcopavanello** [comment]
Please, try to manually delete the folder in the path and then re-install the latest 3.5 version add-on.

**Comment by shankarsivarajan** [comment]
That didn't work, but I found the problem: at least on Windows, the name of the zipped addon folder can't have a "." in it. Unzipping, renaming, and rezipping solved it.

**Comment by shankarsivarajan** [comment]
Of course, the _real_ mistake was me downloading the code from GitHub instead of [3d-wolf.com](https://3d-wolf.com/products/materials/rl) as I did the previous version.
